// ⚠️ PLACEHOLDER — DO NOT USE AS-IS ⚠️
//
// This file is normally auto-generated by the FlutterFire CLI and is
// unique to *your* Firebase project. The values below are dummy
// placeholders and will NOT work — Firebase.initializeApp() will fail
// with an invalid-api-key error until you regenerate this file.
//
// To generate the real version:
//   1. dart pub global activate flutterfire_cli
//   2. flutterfire configure
//      (log in, pick/create your Firebase project, select the platforms
//      you're targeting — e.g. android, ios)
// This overwrites this exact file with your project's real credentials.
// See README § "Connecting Firebase" for the full walkthrough.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web — run `flutterfire configure`.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform — run `flutterfire configure`.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZH6OWA8B6krpenk6g31bWxtcu513umh0',
    appId: '1:815376945049:android:e7065f7a8d230e00e20d08',
    messagingSenderId: '815376945049',
    projectId: 'personal-safety-guard-app',
    storageBucket: 'personal-safety-guard-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcn9e-JH379WttqLSocc5s_6nKFxZ7yig',
    appId: '1:815376945049:ios:617941cc7121e6d0e20d08',
    messagingSenderId: '815376945049',
    projectId: 'personal-safety-guard-app',
    storageBucket: 'personal-safety-guard-app.firebasestorage.app',
    iosBundleId: 'com.example.personalSafetyApp',
  );
}
