import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'app.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Uses the options generated by the FlutterFire CLI (`flutterfire
  // configure`), which writes `lib/firebase_options.dart` for you. This
  // avoids relying on Android's native `google-services.json` +
  // `values.xml` resource pipeline, which is easy to misconfigure and
  // fails at runtime with "Failed to load FirebaseOptions from resource"
  // if the Google Services Gradle plugin isn't applied correctly.
  //
  // One-time setup (see README § "Connecting Firebase"):
  //   1. dart pub global activate flutterfire_cli
  //   2. flutterfire configure
  //      (select your Firebase project, then Android/iOS/etc. targets)
  // This generates `lib/firebase_options.dart` — do not hand-write it.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const SafetyGuardApp());
}
